site_name: nerd Documentation
repo_url: https://github.com/edr-choi/nerd
repo_name: nerd
nav:
  - Home: index.md
  - Guides:
      - Quest from a Mac: guides/quest-new-user.md
      - Running NERD on Quest: guides/quest-local-user.md
      - Task Scheduling: guides/task-scheduling.md
      - Containerized ShapeMapper: guides/shapemapper-containers.md
      - Create Samples: guides/sample-organization.md
      - NMR Kinetics: guides/nmr-kinetics.md
      - Modification Counting: guides/probe-mutcount.md
      - Probe Timecourse: guides/probe-timecourse.md
      - Temperature Gradients: guides/tempgrad-fit.md
  - CLI Reference:
      - create: cli/create.md
      - nmr_create: cli/nmr_create.md
      - nmr_kinetic_fit: cli/nmr_kinetic_fit.md
      - mut_count: cli/mut_count.md
      - probe_timecourse: cli/probe_timecourse.md
      - tempgrad_fit: cli/tempgrad_fit.md
theme:
  name: material
  palette:
    - scheme: default
      primary: white
      accent: light blue
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy
plugins:
  - search
  - include-markdown
markdown_extensions:
  - toc
  - admonition
  - codehilite
